import type { TripIdea } from "@/features/ideas/ideaTypes";

export const mockIdeas: TripIdea[] = [
  {
    id: "teamlab-borderless",
    tripId: "japan-2028",
    title: "teamLab Borderless",
    description:
      "Interactief museum met lichtinstallaties. Goed vroeg plannen vanwege drukte.",
    category: "activity",
    tags: ["Tokyo", "kunst", "regenplan"],
    city: "Tokyo",
    locationName: "Azabudai Hills",
    googleMapsUrl: "https://maps.google.com/?q=teamLab+Borderless+Tokyo",
    websiteUrl: "https://www.teamlab.art/e/borderless-azabudai/",
    notes: "Tickets vooraf checken.",
    customsNotes: "Praat zacht in de installaties en blijf bij de looprichting.",
    showInSchedule: true,
    scheduleDate: "2028-04-20",
    startTime: "10:00",
    endTime: "12:00",
    status: "maybe",
    priority: "high",
    addedBy: "alex",
    createdAt: new Date("2026-05-20T10:00:00.000Z"),
    updatedAt: new Date("2026-05-20T10:00:00.000Z"),
  },
  {
    id: "fushimi-inari",
    tripId: "japan-2028",
    title: "Fushimi Inari vroeg in de ochtend",
    description:
      "Wandeling langs de rode torii-poorten voordat het te druk wordt.",
    category: "sightseeing",
    tags: ["Kyoto", "tempel", "wandelen"],
    city: "Kyoto",
    locationName: "Fushimi Inari-taisha",
    googleMapsUrl: "https://maps.google.com/?q=Fushimi+Inari+Taisha",
    websiteUrl: "https://inari.jp/en/",
    notes: "Neem water mee en ga eventueel niet helemaal naar boven.",
    customsNotes:
      "Bij heiligdommen rustig bewegen en niet midden op het pad blijven staan.",
    showInSchedule: true,
    scheduleDate: "2028-04-24",
    startTime: "07:30",
    endTime: "10:00",
    status: "planned",
    priority: "high",
    addedBy: "alex",
    createdAt: new Date("2026-05-21T08:30:00.000Z"),
    updatedAt: new Date("2026-05-21T08:30:00.000Z"),
  },
  {
    id: "ichiran-shibuya",
    tripId: "japan-2028",
    title: "Ramen bij Ichiran",
    description:
      "Laagdrempelige ramenplek met handig bestelsysteem. Leuk voor de eerste dagen.",
    category: "restaurant",
    tags: ["Tokyo", "ramen", "makkelijk"],
    city: "Tokyo",
    locationName: "Ichiran Shibuya",
    googleMapsUrl: "https://maps.google.com/?q=Ichiran+Shibuya",
    websiteUrl: "https://en.ichiran.com/",
    customsNotes: "Betaal vooraf via de automaat en houd de rij compact.",
    showInSchedule: true,
    scheduleDate: "2028-04-19",
    startTime: "18:30",
    status: "idea",
    priority: "medium",
    addedBy: "alex",
    createdAt: new Date("2026-05-22T11:15:00.000Z"),
    updatedAt: new Date("2026-05-22T11:15:00.000Z"),
  },
  {
    id: "suica-practical",
    tripId: "japan-2028",
    title: "Suica of Pasmo regelen",
    description:
      "Voor vervoer en kleine betalingen. Check vooraf wat op iPhone en Android werkt.",
    category: "practical",
    tags: ["vervoer", "voor vertrek", "Tokyo"],
    locationName: "Luchthaven of Wallet-app",
    notes: "Ook handig voor vending machines.",
    showInSchedule: false,
    status: "idea",
    priority: "medium",
    addedBy: "alex",
    createdAt: new Date("2026-05-23T09:45:00.000Z"),
    updatedAt: new Date("2026-05-23T09:45:00.000Z"),
  },
  {
    id: "nintendo-osaka",
    tripId: "japan-2028",
    title: "Nintendo Osaka",
    description:
      "Merchandise winkel in Umeda. Kan gecombineerd worden met winkels en eten.",
    category: "shop",
    tags: ["Osaka", "winkel", "cadeaus"],
    city: "Osaka",
    locationName: "Daimaru Umeda",
    googleMapsUrl: "https://maps.google.com/?q=Nintendo+Osaka",
    websiteUrl: "https://www.nintendo.com/jp/officialstore/",
    showInSchedule: false,
    status: "maybe",
    priority: "low",
    addedBy: "alex",
    createdAt: new Date("2026-05-24T16:10:00.000Z"),
    updatedAt: new Date("2026-05-24T16:10:00.000Z"),
  },
];
